const USERS=[
    {
        userName: "Ritiksha Ingle",
        imgUrl: "https://i.pravatar.cc/150?img=1",
        age: 20,
        city: "Nagpur",
      },
      {
        userName: "Aarav Mehta",
        imgUrl: "https://i.pravatar.cc/150?img=2",
        age: 25,
        city: "Mumbai",
      },
      {
        userName: "Sneha Patel",
        imgUrl: "https://i.pravatar.cc/150?img=3",
        age: 22,
        city: "Ahmedabad",
      },
      {
        userName: "Karthik Reddy",
        imgUrl: "https://i.pravatar.cc/150?img=4",
        age: 28,
        city: "Hyderabad",
      },
      {
        userName: "Priya Sharma",
        imgUrl: "https://i.pravatar.cc/150?img=5",
        age: 24,
        city: "Delhi",
      },
      {
        userName: "Rahul Verma",
        imgUrl: "https://i.pravatar.cc/150?img=6",
        age: 30,
        city: "Bangalore",
      },
      {
        userName: "Ananya Iyer",
        imgUrl: "https://i.pravatar.cc/150?img=7",
        age: 26,
        city: "Chennai",
      },
      {
        userName: "Rohan Singh",
        imgUrl: "https://i.pravatar.cc/150?img=8",
        age: 27,
        city: "Pune",
      },
      {
        userName: "Pooja Nair",
        imgUrl: "https://i.pravatar.cc/150?img=9",
        age: 23,
        city: "Kolkata",
      },
      {
        userName: "Vikram Joshi",
        imgUrl: "https://i.pravatar.cc/150?img=10",
        age: 29,
        city: "Jaipur",
      },
      {
        userName: "Meera Das",
        imgUrl: "https://i.pravatar.cc/150?img=11",
        age: 21,
        city: "Lucknow",
      },
      {
        userName: "Aditya Malhotra",
        imgUrl: "https://i.pravatar.cc/150?img=1",
        age: 27,
        city: "Delhi",
      },
      {
        userName: "Neha Sinha",
        imgUrl: "https://i.pravatar.cc/150?img=2",
        age: 23,
        city: "Mumbai",
      },
      {
        userName: "Arjun Das",
        imgUrl: "https://i.pravatar.cc/150?img=3",
        age: 30,
        city: "Bangalore",
      },
      {
        userName: "Kavya Iyer",
        imgUrl: "https://i.pravatar.cc/150?img=4",
        age: 25,
        city: "Chennai",
      },
      {
        userName: "Rajat Mehta",
        imgUrl: "https://i.pravatar.cc/150?img=5",
        age: 28,
        city: "Pune",
      },
      {
        userName: "Tanya Chawla",
        imgUrl: "https://i.pravatar.cc/150?img=6",
        age: 22,
        city: "Kolkata",
      },
      {
        userName: "Vishal Nair",
        imgUrl: "https://i.pravatar.cc/150?img=7",
        age: 29,
        city: "Hyderabad",
      },
      {
        userName: "Sanya Kapoor",
        imgUrl: "https://i.pravatar.cc/150?img=8",
        age: 26,
        city: "Ahmedabad",
      },
      {
        userName: "Rohit Sharma",
        imgUrl: "https://i.pravatar.cc/150?img=9",
        age: 31,
        city: "Jaipur",
      },
      {
        userName: "Divya Arora",
        imgUrl: "https://i.pravatar.cc/150?img=10",
        age: 24,
        city: "Indore",
      },
      {
        userName: "Sahil Verma",
        imgUrl: "https://i.pravatar.cc/150?img=11",
        age: 32,
        city: "Lucknow",
      },
      {
        userName: "Megha Pandey",
        imgUrl: "https://i.pravatar.cc/150?img=12",
        age: 27,
        city: "Bhopal",
      },
      {
        userName: "Harsh Gupta",
        imgUrl: "https://i.pravatar.cc/150?img=13",
        age: 26,
        city: "Chandigarh",
      },
      {
        userName: "Ishita Saxena",
        imgUrl: "https://i.pravatar.cc/150?img=14",
        age: 25,
        city: "Surat",
      },
      {
        userName: "Kunal Joshi",
        imgUrl: "https://i.pravatar.cc/150?img=15",
        age: 30,
        city: "Nagpur",
      },
      {
        userName: "Rhea Menon",
        imgUrl: "https://i.pravatar.cc/150?img=16",
        age: 23,
        city: "Patna",
      },
      {
        userName: "Amit Thakur",
        imgUrl: "https://i.pravatar.cc/150?img=17",
        age: 29,
        city: "Bhubaneswar",
      },
      {
        userName: "Sneha Rajput",
        imgUrl: "https://i.pravatar.cc/150?img=18",
        age: 28,
        city: "Raipur",
      },
      {
        userName: "Manav Sethi",
        imgUrl: "https://i.pravatar.cc/150?img=19",
        age: 31,
        city: "Ranchi",
      },
      {
        userName: "Pallavi Deshmukh",
        imgUrl: "https://i.pravatar.cc/150?img=20",
        age: 24,
        city: "Guwahati",
      },
      {
        userName: "Yash Tiwari",
        imgUrl: "https://i.pravatar.cc/150?img=21",
        age: 26,
        city: "Shimla",
      },
      {
        userName: "Nidhi Mishra",
        imgUrl: "https://i.pravatar.cc/150?img=22",
        age: 27,
        city: "Dehradun",
      },
    ];

export {USERS};